###
# Copyright (C) 2014 Talend Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
registry.client.enabled=true

registry.url=http://localhost:8040/services/registry/lookup
registry.client.service.blacklist={http://www.talend.org/esb/sam/MonitoringService/v1}MonitoringServiceService,{http://docs.oasis-open.org/ws-sx/ws-trust/200512/}SecurityTokenService,{http://service.registry.esb.talend.org/}RegistryRestServiceImpl

# Authentication method BASIC,SAML,NO
registry.authentication = NO

#BASIC authentication
registry.authentication.user = karaf
registry.authentication.password = karaf

#SAML authentication
ws-security.username = tadmin
ws-security.password = tadmin
ws-security.sts.token.username = myclientkey
ws-security.sts.token.properties = clientKeystore.properties
ws-security.encryption.username = mystskey
ws-security.encryption.properties = clientKeystore.properties
sts.wsdl.location = http://localhost:8042/services/SecurityTokenService/UT?wsdl
sts.service.name = {http://docs.oasis-open.org/ws-sx/ws-trust/200512/}SecurityTokenService
sts.endpoint.name ={http://docs.oasis-open.org/ws-sx/ws-trust/200512/}UT_Port
sts.tokentype = http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0
sts.keytype = http://docs.oasis-open.org/ws-sx/ws-trust/200512/Bearer
